/**
 * HA-03: plain-language diagnosis of why a dashboard could not be loaded.
 *
 * The round-1 UAT defect HA-03 ("Some dashboards will load but others don't")
 * was NOT a parser defect — every storage-mode dashboard on the reference
 * instance parses losslessly. It was two failures of HONESTY:
 *
 *  1. `DashboardBrowser` always lists a synthesised "Overview" entry it has
 *     never verified exists. Home Assistant excludes the default dashboard from
 *     `lovelace/dashboards/list`, and while Overview is still auto-generated by
 *     the `original-states` strategy there is no stored config to read — so
 *     `lovelace/config` answers `config_not_found` and HAVDM surfaced Home
 *     Assistant's raw "No config found." string.
 *  2. The load paths announced success regardless of the outcome.
 *
 * Per THE VISION (answers 5 and 8), a dashboard HAVDM cannot fully parse must
 * degrade HONESTLY: say what could not be handled, in words a non-expert can
 * act on. Silent failure — and a raw upstream error string — is the defect.
 *
 * These helpers are pure and live in `utils/` so both the fetch side
 * (`DashboardBrowser`) and the parse side (`yamlService`) share one voice, and
 * so the wording is unit-testable without driving Electron.
 * ⚠ LAYERING: `utils/` may not import from `services/`.
 */

/** The one remedy that actually works for an auto-generated HA dashboard. */
const TAKE_CONTROL =
  'Open it in Home Assistant, use the dashboard menu to choose "Take control", ' +
  'then download it again.';

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

/**
 * True when Home Assistant's answer means "this dashboard has no stored
 * configuration", rather than a transport or permission failure. HA reports it
 * as the `config_not_found` error code, which reaches us as the message
 * "No config found." once it has crossed the IPC boundary.
 */
export const isConfigNotFound = (rawError: string | undefined | null): boolean =>
  /config_not_found|no config found/i.test(rawError ?? '');

/**
 * Turn a failed `lovelace/config` fetch into something a non-expert can act on.
 *
 * @param rawError Home Assistant's own message, as surfaced by the IPC handler.
 * @param isDefault Whether this is the synthesised default ("Overview") entry —
 *   the one HAVDM lists without ever having verified it exists.
 * @param title The dashboard's title, for a message that names what failed.
 */
export function describeDashboardFetchFailure(
  rawError: string | undefined | null,
  { isDefault, title }: { isDefault: boolean; title: string },
): string {
  if (isConfigNotFound(rawError)) {
    return isDefault
      ? `Home Assistant builds "${title}" automatically and does not store a copy that HAVDM can read. ` +
          `To edit it here, ${TAKE_CONTROL.charAt(0).toLowerCase()}${TAKE_CONTROL.slice(1)}`
      : `Home Assistant has no stored configuration for "${title}" — it is generated automatically. ` +
          TAKE_CONTROL;
  }

  const detail = (rawError ?? '').trim();
  return detail
    ? `Could not download "${title}" from Home Assistant: ${detail}`
    : `Could not download "${title}" from Home Assistant.`;
}

/**
 * Explain, in plain language, why a parsed YAML payload is not a dashboard
 * HAVDM can put on the canvas — or `null` when it is one.
 *
 * ⚠ This deliberately does NOT name the dashboard: it is called from
 * `yamlService.parseDashboard`, which serves file-open, HA-download and
 * preset-import alike. Each caller prefixes its own context.
 */
export function diagnoseDashboardPayload(data: unknown): string | null {
  if (data === null || data === undefined || data === '') {
    return 'It is empty — there is no dashboard content to load.';
  }

  if (Array.isArray(data)) {
    return 'It contains a list rather than a set of dashboard settings, so it is not a dashboard.';
  }

  if (!isRecord(data)) {
    return 'It does not contain dashboard settings, so it is not a dashboard.';
  }

  if (!('views' in data) || data.views === null || data.views === undefined) {
    // A Home Assistant "strategy" dashboard is built on the fly by the frontend
    // and stores no views at all. This is the shape behind HA-03's default
    // "Overview" entry, and it is a legitimate dashboard — just not one that
    // has any authored content for HAVDM to edit.
    const strategy = data.strategy;
    if (strategy !== undefined && strategy !== null) {
      const type = isRecord(strategy) && typeof strategy.type === 'string' ? strategy.type : null;
      const named = type ? `the Home Assistant "${type}" strategy` : 'a Home Assistant strategy';
      return (
        `It is built automatically by ${named}, so it stores no views for HAVDM to edit. ` +
        TAKE_CONTROL
      );
    }
    return 'It has no "views" section, so there is nothing to place on the canvas.';
  }

  if (!Array.isArray(data.views)) {
    return 'Its "views" entry is not a list of views, so HAVDM cannot read the layout.';
  }

  return null;
}
