# Home Overview Dashboard Template
# A comprehensive main dashboard showing at-a-glance status of the entire home
#
# This template provides:
# - Weather forecast
# - Person/presence tracking
# - Quick action scenes
# - Summary badges (lights on, doors open, etc.)
# - Energy usage overview
# - Security status
# - Upcoming calendar events

title: Home Overview
views:
  - title: Home
    path: home
    type: custom:grid-layout
    layout:
      grid_template_columns: repeat(12, 1fr)
      grid_template_rows: repeat(auto-fill, 56px)
      grid_gap: 8px
    cards:
      # Welcome Header
      - type: markdown
        content: |
          # Welcome Home
          {{ now().strftime('%A, %B %d, %Y') }}
        view_layout:
          grid_column: 1 / 13
          grid_row: 1 / 2

      # Weather Card
      - type: weather-forecast
        entity: weather.forecast_home
        name: Weather
        view_layout:
          grid_column: 1 / 7
          grid_row: 2 / 6

      # Quick Actions
      - type: horizontal-stack
        view_layout:
          grid_column: 7 / 13
          grid_row: 2 / 4
        cards:
          - type: button
            entity: scene.good_morning
            name: Good Morning
            icon: mdi:weather-sunny
            tap_action:
              action: toggle
          - type: button
            entity: scene.good_night
            name: Good Night
            icon: mdi:weather-night
            tap_action:
              action: toggle
          - type: button
            entity: scene.away
            name: Away
            icon: mdi:exit-run
            tap_action:
              action: toggle
          - type: button
            entity: scene.home
            name: Home
            icon: mdi:home
            tap_action:
              action: toggle

      # Person/Presence Tracking
      - type: entities
        title: Who's Home
        view_layout:
          grid_column: 7 / 13
          grid_row: 4 / 6
        entities:
          - entity: person.john
            name: John
          - entity: person.jane
            name: Jane

      # Status Summary Cards
      - type: glance
        title: Home Status
        view_layout:
          grid_column: 1 / 7
          grid_row: 6 / 8
        entities:
          - entity: sensor.lights_on_count
            name: Lights On
            icon: mdi:lightbulb-on
          - entity: sensor.windows_open_count
            name: Windows Open
            icon: mdi:window-open
          - entity: sensor.doors_unlocked_count
            name: Doors Unlocked
            icon: mdi:door-open
          - entity: binary_sensor.internet_connection
            name: Internet
            icon: mdi:wifi

      # Security Status
      - type: alarm-panel
        entity: alarm_control_panel.home
        name: Security System
        view_layout:
          grid_column: 7 / 13
          grid_row: 6 / 9
        states:
          - armed_home
          - armed_away
          - armed_night
          - disarmed

      # Energy Usage Summary
      - type: entities
        title: Energy Today
        view_layout:
          grid_column: 1 / 7
          grid_row: 8 / 11
        entities:
          - entity: sensor.daily_energy_consumption
            name: Consumption
            icon: mdi:flash
          - entity: sensor.daily_energy_cost
            name: Cost Today
            icon: mdi:currency-usd
          - entity: sensor.current_power_usage
            name: Current Usage
            icon: mdi:power-plug

      # Climate Overview
      - type: glance
        title: Climate
        view_layout:
          grid_column: 7 / 13
          grid_row: 9 / 11
        entities:
          - entity: sensor.living_room_temperature
            name: Living Room
          - entity: sensor.bedroom_temperature
            name: Bedroom
          - entity: sensor.outdoor_temperature
            name: Outside
          - entity: sensor.indoor_humidity
            name: Humidity

      # Calendar Events
      - type: entities
        title: Upcoming Events
        view_layout:
          grid_column: 1 / 13
          grid_row: 11 / 14
        entities:
          - entity: calendar.family
            name: Family Calendar
          - entity: calendar.work
            name: Work Calendar
