/**
 * The shared view-type validator (F1 / UAT defect HA-07).
 *
 * ⭐⭐ EVERY "IS VALID" CASE BELOW IS A MEASUREMENT OF HOME ASSISTANT, NOT AN
 * OPINION ABOUT IT. That distinction is the whole reason this module exists: the
 * loop it replaces was built from what someone believed HA required, and every
 * one of those beliefs turned out to be wrong. So before a single rule was
 * written, each shape was deployed to a real instance and rendered in a real
 * browser (`ha-test.home.local`, writable per Phase 7 amendment-04; both probe
 * dashboards were torn down afterwards). What was observed, 2026-08-04:
 *
 *   | shape                                   | HA accepted | rendered          | error cards |
 *   | untitled view (no `title` key)          | yes         | masonry, 1 card   | 0           |
 *   | view-level strategy (original-states)   | yes         | 50 cards          | 0           |
 *   | `type: sections`, no top-level `cards`  | yes         | sections, 1 grid  | 0           |
 *   | typeless + `sections` (HAVDM's export)  | yes         | sections, 1 grid  | 0           |
 *   | dashboard-level strategy, no `views`    | yes         | 50 cards          | 0           |
 *
 * Corroborated read-only on the reference instance (`ha.home.local`): THREE of
 * its nineteen live views have no top-level `cards` array and work fine —
 * `family-dashboard`, `admin-dashboard` and `environmental-control`, the last
 * being typeless-with-`sections`, precisely the shape HAVDM's own export emits.
 *
 * ⚠ RED-LEG HONESTY. These tests CANNOT be red-legged by `git stash push -u src/`:
 * the module under test does not exist on base, so stashing makes them fail at
 * import rather than at an assertion, and a red leg that fails for the wrong
 * reason measures nothing. The legs that genuinely measure the bug are in
 * `tests/unit/DeployDialog.spec.tsx`, which drives a component that DOES exist
 * on base and fails there with the real defect's message. This file's job is
 * breadth over the rule set, not proof that the rule set was ever broken.
 */

import { describe, expect, it } from 'vitest';
import {
  DashboardValidationError,
  assertDeployable,
  describeView,
  resolveViewKind,
  validateDashboardForDeploy,
  validateView,
} from '../../src/services/dashboardValidation';
import type { DashboardConfig, View } from '../../src/types/dashboard';

const dashboard = (views: View[]): DashboardConfig => ({ title: 'Test', views });

describe("resolveViewKind — Home Assistant's own fallback chain", () => {
  // Read verbatim out of the reference instance's served frontend bundle
  // (HA 2026.7.4, webpack module 25932):
  //   type ? type : panel ? "panel" : sections ? "sections" : cards ? "masonry" : "sections"
  it('prefers an explicit type', () => {
    expect(resolveViewKind({ type: 'sections', sections: [] })).toBe('sections');
    expect(resolveViewKind({ type: 'masonry', cards: [] })).toBe('cards');
    expect(resolveViewKind({ type: 'sidebar', cards: [] })).toBe('cards');
  });

  it('infers sections from the `sections` key when there is no type', () => {
    // ⭐ THE SHAPE HAVDM'S OWN EXPORT EMITS, and the reason HA renders it while
    // HAVDM's canvas does not (`GridCanvas.tsx:295` demands a strict match).
    expect(resolveViewKind({ sections: [] })).toBe('sections');
  });

  it('resolves panel before sections, and strategy before everything', () => {
    expect(resolveViewKind({ panel: true, cards: [] })).toBe('panel');
    expect(resolveViewKind({ strategy: { type: 'original-states' } })).toBe('strategy');
    // A strategy view that also carries a type is still generated by HA.
    expect(resolveViewKind({ type: 'sections', strategy: { type: 'map' } })).toBe('strategy');
  });

  it('falls back to cards for a bare view', () => {
    expect(resolveViewKind({ cards: [] })).toBe('cards');
    expect(resolveViewKind({})).toBe('cards');
  });
});

describe('describeView — how a view is named in an error', () => {
  it('uses the title when there is one', () => {
    expect(describeView({ title: 'Energy', cards: [] }, 1)).toBe('View "Energy"');
  });

  it('falls back to a 1-based ordinal for an untitled view', () => {
    // ⚠ The old loop demanded a title precisely so it could interpolate one.
    // Removing that demand means messages must never read `View "undefined"`.
    expect(describeView({ cards: [] }, 2)).toBe('View 3');
    expect(describeView({ title: '', cards: [] }, 0)).toBe('View 1');
  });
});

describe('the four shapes the old validator wrongly refused', () => {
  it('(1) a sections view validates — its cards live under `sections[].cards`', () => {
    // ⭐ HA-07 ITSELF. The old rule was `!view.cards || !Array.isArray(view.cards)`,
    // which this view fails and Home Assistant does not.
    const view: View = {
      title: 'Energy',
      type: 'sections',
      sections: [
        { type: 'grid', cards: [{ type: 'markdown', content: 'a' }] },
        { type: 'grid', cards: [{ type: 'tile', entity: 'sensor.x' }] },
      ],
    } as View;
    expect(validateView(view, 0)).toEqual([]);
    expect(validateDashboardForDeploy(dashboard([view]))).toEqual([]);
  });

  it('(1b) a TYPELESS sections view validates — the shape HAVDM itself exports', () => {
    const view: View = {
      title: 'Energy',
      sections: [{ type: 'grid', cards: [{ type: 'markdown', content: 'a' }] }],
    } as View;
    expect(validateView(view, 0)).toEqual([]);
  });

  it('(2) an untitled view validates — Lovelace does not require a title', () => {
    expect(validateView({ cards: [{ type: 'markdown', content: 'a' }] } as View, 0)).toEqual([]);
    expect(validateView({ title: '', cards: [] } as View, 0)).toEqual([]);
  });

  it('(3) a strategy view validates with no cards at all', () => {
    // Home Assistant GENERATES this view's cards at render time — measured at 50
    // of them for `original-states`, with zero error cards.
    const view = { title: 'Generated', strategy: { type: 'original-states' } } as View;
    expect(validateView(view, 0)).toEqual([]);
  });

  it('(5) a DASHBOARD-level strategy validates with no `views` key at all', () => {
    // ⭐ THE FIFTH DEFECT, found while investigating F1 and squarely the same
    // family. `types/dashboard.ts` already says HAVDM "must simply carry one
    // through untouched, or deploying replaces the user's generated dashboard
    // with nothing" — and the old check refused it as "appears to be empty".
    const config = { strategy: { type: 'original-states' } } as DashboardConfig;
    expect(validateDashboardForDeploy(config)).toEqual([]);
  });
});

describe('shapes Home Assistant accepts that must therefore not be refused', () => {
  it('an empty `cards` array is fine', () => {
    expect(validateView({ title: 'Empty', cards: [] }, 0)).toEqual([]);
  });

  it('a content-less view is fine — HA renders it empty rather than erroring', () => {
    // ⚠ DELIBERATE, AND SIGNED OFF. Refusing this would recreate the exact
    // property that caused HA-07: HAVDM being stricter than the consumer.
    expect(validateView({ title: 'Nothing here' }, 0)).toEqual([]);
    expect(validateDashboardForDeploy(dashboard([{ title: 'Nothing here' }]))).toEqual([]);
  });

  it('a sections view with no sections yet is fine', () => {
    expect(validateView({ title: 'New', type: 'sections', sections: [] }, 0)).toEqual([]);
  });

  it('a section with no cards yet is fine', () => {
    const view = { type: 'sections', sections: [{ type: 'grid' }] } as View;
    expect(validateView(view, 0)).toEqual([]);
  });

  it('a panel view and a layout-card view both validate', () => {
    expect(
      validateView({ title: 'Panel', panel: true, cards: [{ type: 'map' }] } as View, 0),
    ).toEqual([]);
    expect(
      validateView({ title: 'Grid', type: 'custom:grid-layout', cards: [] } as View, 0),
    ).toEqual([]);
  });
});

describe('genuinely malformed views still fail, naming what is wrong', () => {
  const messageOf = (view: unknown, index = 0) =>
    validateView(view as View, index).map((error) => error.message);

  it('a `cards` property that is not a list', () => {
    expect(messageOf({ title: 'Broken', cards: 'not a list' })).toEqual([
      'View "Broken" has a "cards" property that is not a list of cards.',
    ]);
  });

  it('a `sections` property that is not a list', () => {
    expect(messageOf({ title: 'Broken', sections: {} })).toEqual([
      'View "Broken" has a "sections" property that is not a list of sections.',
    ]);
  });

  it('a section whose `cards` is not a list — named down to the section', () => {
    expect(
      messageOf({ title: 'Energy', type: 'sections', sections: [{ type: 'grid' }, { cards: 7 }] }),
    ).toEqual(['View "Energy", section 2 has a "cards" property that is not a list of cards.']);
  });

  it('a section that is not a section at all', () => {
    expect(messageOf({ title: 'Energy', sections: ['nope'] })).toEqual([
      'View "Energy", section 1 is not a valid section.',
    ]);
  });

  it('a strategy with no type — Home Assistant could not run it', () => {
    expect(messageOf({ title: 'Generated', strategy: {} })).toEqual([
      'View "Generated" has a "strategy" with no "type" — Home Assistant needs the strategy\'s type to generate the view.',
    ]);
  });

  it('a view that is not a view', () => {
    expect(messageOf(null, 2)).toEqual([
      'View 3 is not a valid view — expected a set of view properties, found nothing.',
    ]);
  });

  it('names an UNTITLED offending view by its position', () => {
    // The regression this guards: dropping the mandatory-title rule must not
    // produce `View "undefined" has a "cards" property…`.
    const messages = messageOf({ cards: 'not a list' }, 1);
    expect(messages).toEqual(['View 2 has a "cards" property that is not a list of cards.']);
    expect(messages[0]).not.toContain('undefined');
  });
});

describe('reporting behaviour', () => {
  it('reports EVERY problem, not just the first', () => {
    // The old loop threw on the first offending view, so a user with three
    // problems learned about them one deploy at a time.
    const errors = validateDashboardForDeploy(
      dashboard([
        { title: 'A', cards: 'x' },
        { title: 'B', cards: [] },
        { title: 'C', sections: 3 },
      ] as unknown as View[]),
    );
    expect(errors).toHaveLength(2);
    expect(errors.map((error) => error.viewIndex)).toEqual([0, 2]);
  });

  it('still refuses a dashboard with no views and no strategy', () => {
    expect(validateDashboardForDeploy(dashboard([]))).toEqual([
      {
        viewIndex: null,
        message: 'Dashboard must contain at least one view. Your dashboard appears to be empty.',
      },
    ]);
  });

  it('still reports a missing config', () => {
    expect(validateDashboardForDeploy(null)).toEqual([
      { viewIndex: null, message: 'No dashboard configuration to deploy.' },
    ]);
  });

  it('a dashboard-level strategy with no type is reported', () => {
    const config = { strategy: {} } as unknown as DashboardConfig;
    expect(validateDashboardForDeploy(config)[0].message).toContain(
      "needs the strategy's type to generate the dashboard",
    );
  });
});

describe('assertDeployable', () => {
  it('throws a DashboardValidationError carrying every error', () => {
    let thrown: unknown;
    try {
      assertDeployable(dashboard([{ title: 'A', cards: 'x' }] as unknown as View[]));
    } catch (error) {
      thrown = error;
    }
    expect(thrown).toBeInstanceOf(DashboardValidationError);
    expect((thrown as DashboardValidationError).errors).toHaveLength(1);
    expect((thrown as Error).message).toContain('is not a list of cards');
  });

  it('is distinguishable from an ordinary Error — this is what stops the connection blame', () => {
    // ⭐ The class IS the fix for defect 4: `DeployDialog` decides which
    // sub-line to show by asking whether the failure was a validation failure.
    expect(new DashboardValidationError([]) instanceof Error).toBe(true);
    expect(new Error('network down') instanceof DashboardValidationError).toBe(false);
  });

  it('does not throw for a valid dashboard', () => {
    expect(() => assertDeployable(dashboard([{ title: 'A', cards: [] }]))).not.toThrow();
  });
});

describe('⚠ THE VALIDATOR NEVER MUTATES THE CONFIG', () => {
  it('leaves the dashboard byte-identical — it reports, the user decides', () => {
    // The tempting "fix" for HA-07 is to insert `cards: []` on any view that
    // lacks one so the old rule passes. That would be HAVDM editing the user's
    // dashboard behind their back to satisfy its own bug, and deploy sends this
    // object VERBATIM (slice B0) — so the edit would reach Home Assistant.
    const config = dashboard([
      { title: 'Energy', type: 'sections', sections: [{ type: 'grid', cards: [] }] } as View,
      { cards: [{ type: 'markdown', content: 'a' }] } as View,
      { title: 'Generated', strategy: { type: 'original-states' } } as View,
    ]);
    const before = JSON.parse(JSON.stringify(config));
    const viewRefs = config.views.map((view) => view);

    validateDashboardForDeploy(config);
    assertDeployable(config);

    expect(config).toEqual(before);
    expect(config.views[0]).not.toHaveProperty('cards');
    // Reference equality too: nothing was cloned-and-replaced either.
    config.views.forEach((view, index) => expect(view).toBe(viewRefs[index]));
  });
});
