/**
 * HA-03 regression coverage — "Some dashboards will load but others don't".
 *
 * The round-1 defect was NOT a parser bug: every storage-mode dashboard on the
 * reference instance parses losslessly. It was that HAVDM failed DISHONESTLY —
 * it listed a default "Overview" entry it had never verified exists, then
 * surfaced Home Assistant's raw `config_not_found` string, and the load paths
 * announced success regardless of the outcome.
 *
 * Per THE VISION (answers 5 and 8) an honest, specific failure is the product
 * requirement, so these tests pin the WORDING and the SHAPE of every failure —
 * not merely that some failure occurred.
 *
 * ⚠ amendment-03 §7: HA-03's UAT card cited `tests/e2e/live-preview-deploy.spec.ts`
 * as `auto_covered: Y`. That file is 26 tests of `expect(true).toBe(true)` with
 * 85 TODOs and zero real assertions, so HA-03 in fact had NO automated coverage.
 * This file plus `tests/integration/dashboard-load-honesty.spec.ts` supply it.
 */
import { describe, it, expect } from 'vitest';
import {
  describeDashboardFetchFailure,
  diagnoseDashboardPayload,
  isConfigNotFound,
} from '../../src/utils/dashboardLoadDiagnostics';
import { yamlService } from '../../src/services/yamlService';
import { useDashboardStore } from '../../src/store/dashboardStore';
import * as yaml from 'js-yaml';

describe('isConfigNotFound', () => {
  it('recognises the message Home Assistant actually sends', () => {
    // The literal string the tester saw, via the IPC error round-trip.
    expect(isConfigNotFound('No config found.')).toBe(true);
    // And the raw HA error code, in case a caller passes it through instead.
    expect(isConfigNotFound('config_not_found')).toBe(true);
  });

  it('does not swallow unrelated failures', () => {
    expect(isConfigNotFound('Request timeout')).toBe(false);
    expect(isConfigNotFound('WebSocket is not connected')).toBe(false);
    expect(isConfigNotFound(undefined)).toBe(false);
    expect(isConfigNotFound(null)).toBe(false);
    expect(isConfigNotFound('')).toBe(false);
  });
});

describe('describeDashboardFetchFailure', () => {
  it('explains the DEFAULT dashboard failure the round-1 tester actually hit', () => {
    // Reproduced live against ha.home.local (HA 2026.7.4) read-only:
    // `lovelace/config` with url_path=null answers config_not_found, because
    // Overview is still generated by the original-states strategy.
    const message = describeDashboardFetchFailure('No config found.', {
      isDefault: true,
      title: 'Overview',
    });

    expect(message).toContain('Overview');
    expect(message).toContain('automatically');
    // The remedy has to be in the message — this is the whole point of the fix.
    expect(message).toContain('Take control');
    // And Home Assistant's raw string must NOT be what the user reads.
    expect(message).not.toContain('No config found');
  });

  it('explains the same failure for a non-default dashboard', () => {
    const message = describeDashboardFetchFailure('No config found.', {
      isDefault: false,
      title: 'Energy & Power',
    });

    expect(message).toContain('Energy & Power');
    expect(message).toContain('Take control');
    expect(message).not.toContain('No config found');
  });

  it('passes an unrelated failure through, still naming the dashboard', () => {
    // ⚠ Control leg: the helper must not dress up EVERY failure as
    // "take control" — a timeout is a different problem with a different fix.
    const message = describeDashboardFetchFailure('Request timeout', {
      isDefault: false,
      title: 'Control Panel',
    });

    expect(message).toContain('Control Panel');
    expect(message).toContain('Request timeout');
    expect(message).not.toContain('Take control');
  });

  it('still says something useful when Home Assistant sends no message', () => {
    const message = describeDashboardFetchFailure(undefined, {
      isDefault: false,
      title: 'Map',
    });

    expect(message).toContain('Map');
    expect(message.trim().length).toBeGreaterThan(0);
    expect(message).not.toContain('undefined');
  });
});

describe('diagnoseDashboardPayload', () => {
  it('accepts every dashboard shape the reference instance actually returns', () => {
    // Captured read-only from ha.home.local: masonry views, sections views,
    // panel views, a custom:grid-layout view, and a view with no `type` key.
    const shapes: unknown[] = [
      { title: 'T', views: [{ title: 'A', cards: [] }] },
      { views: [{ type: 'sections', sections: [{ type: 'grid', cards: [] }] }] },
      { title: 'T', views: [{ type: 'panel', cards: [{ type: 'map' }] }] },
      { title: 'T', views: [{ type: 'custom:grid-layout', layout: {}, cards: [] }] },
      { title: 'T', theme: 'x', views: [{ title: 'A', path: 'a', cards: [] }] },
      // An empty views list is a legitimate, loadable dashboard.
      { title: 'T', views: [] },
    ];

    for (const shape of shapes) {
      expect(diagnoseDashboardPayload(shape)).toBeNull();
    }
  });

  it('names a Home Assistant STRATEGY dashboard, and its strategy, by name', () => {
    // This is the shape behind HA-03's default entry. The old message —
    // 'Dashboard must contain a "views" array' — was true and useless.
    const problem = diagnoseDashboardPayload({ strategy: { type: 'original-states' } });

    expect(problem).toBeTruthy();
    expect(problem).toContain('original-states');
    expect(problem).toContain('Take control');
    expect(problem).not.toContain('views" array');
  });

  it('still explains a strategy dashboard whose strategy has no type', () => {
    const problem = diagnoseDashboardPayload({ title: 'Home', strategy: {} });

    expect(problem).toBeTruthy();
    expect(problem).toContain('strategy');
    expect(problem).not.toContain('undefined');
  });

  it('does not mistake a normal dashboard that ALSO carries a strategy', () => {
    // Views present wins: there is real authored content to edit.
    expect(
      diagnoseDashboardPayload({
        strategy: { type: 'original-states' },
        views: [{ title: 'A', cards: [] }],
      }),
    ).toBeNull();
  });

  it('distinguishes the remaining unloadable shapes from each other', () => {
    const empty = diagnoseDashboardPayload(null);
    const list = diagnoseDashboardPayload([{ views: [] }]);
    const scalar = diagnoseDashboardPayload('just a string');
    const noViews = diagnoseDashboardPayload({ title: 'T' });
    const badViews = diagnoseDashboardPayload({ title: 'T', views: {} });

    for (const problem of [empty, list, scalar, noViews, badViews]) {
      expect(problem).toBeTruthy();
    }
    expect(empty).toContain('empty');
    expect(list).toContain('list');
    expect(noViews).toContain('views');
    expect(badViews).toContain('views');
    // ⭐ Each shape must get its OWN explanation — a single generic string for
    // all of them is what the old code did, and is what made HA-03 opaque.
    expect(new Set([empty, list, scalar, noViews, badViews]).size).toBe(5);
  });
});

describe('yamlService.parseDashboard surfaces the diagnosis', () => {
  it('rejects a strategy dashboard with the plain-language reason', () => {
    // Exactly the production path: HA config -> yaml.dump -> parseDashboard.
    const yamlString = yaml.dump(
      { strategy: { type: 'original-states' } },
      { indent: 2, lineWidth: -1, noRefs: true },
    );

    const result = yamlService.parseDashboard(yamlString);

    expect(result.success).toBe(false);
    expect(result.error).toContain('original-states');
    expect(result.error).toContain('Take control');
  });

  it('still loads every real dashboard shape', () => {
    const yamlString = yaml.dump(
      {
        title: 'Control Panel',
        views: [{ title: 'A', type: 'masonry', cards: [{ type: 'tile' }] }],
      },
      { indent: 2, lineWidth: -1, noRefs: true },
    );

    const result = yamlService.parseDashboard(yamlString);

    expect(result.success).toBe(true);
    expect(result.data?.views).toHaveLength(1);
  });
});

describe('a refused dashboard never destroys the one already open', () => {
  const GOOD = 'title: Control Panel\nviews:\n  - title: Home\n    cards: []\n';
  const STRATEGY = 'strategy:\n  type: original-states\n';

  it('keeps the loaded config and filePath when the next load fails', () => {
    // ⭐ The store used to set `{ config: null, filePath: null }` on a parse
    // failure, so opening an unreadable dashboard WIPED the user's work off the
    // canvas. THE VISION makes "never silently destroy user data" structural,
    // and the owner's ruling on HA-03 was explicit: leave the canvas untouched.
    useDashboardStore.getState().loadDashboard(GOOD, '/tmp/good.yaml');
    expect(useDashboardStore.getState().config?.title).toBe('Control Panel');

    useDashboardStore.getState().loadDashboard(STRATEGY, '/tmp/overview.yaml');

    const state = useDashboardStore.getState();
    expect(state.error).toBeTruthy();
    expect(state.error).toContain('original-states');
    // The work that WAS open is still open.
    expect(state.config?.title).toBe('Control Panel');
    expect(state.filePath).toBe('/tmp/good.yaml');
  });

  it('still reports a first-load failure with nothing open', () => {
    // ⚠ Control leg: preserving the config must not turn a genuine
    // nothing-is-loaded failure into a silent one.
    useDashboardStore.setState({ config: null, filePath: null, error: null });

    useDashboardStore.getState().loadDashboard(STRATEGY, '/tmp/overview.yaml');

    const state = useDashboardStore.getState();
    expect(state.config).toBeNull();
    expect(state.error).toBeTruthy();
  });
});
